# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/inventory.json
---
all:
  children:
    vps:
      hosts:
        rnd-vps-01:
          ansible_host: "{{ vault_vps_host_ip }}"
