---
driver:
  name: docker
platforms:
  - name: vps-test
    image: "cisagov/docker-debian13-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    published_ports:
      - "8080:80"
      - "8443:443"
    groups:
      - vps
provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: /home/kchou/Code/vps-ansible/roles
      vault_password_file: /home/kchou/Code/vps-ansible/.vault-password
      inventory: /home/kchou/Code/vps-ansible/inventory/prod/hosts.yml
  inventory:
    host_vars:
      vps-test:
        vault_vps_host_ip: "127.0.0.1"
        vault_domain_name: "localhost"
        vault_ssh_port: "22"
        vault_ansible_user: "root"
        vault_ansible_become_password: ""
        ansible_user: "root"
        ansible_port: "22"
        domain_name: "localhost"
        vault_traefik_cloudflare_dns_api_token: "test-token"
        vault_vaultwarden_admin_token: "test-token"
        traefik_cloudflare_dns_api_token: "test-token"
        traefik_image: traefik
        traefik_image_tag: v3.6.10
        traefik_container_name: traefik
        traefik_acme_email: ""
        traefik_acme_ca_server: https://acme-v02.api.letsencrypt.org/directory
        traefik_dns_challenge_provider: cloudflare
        traefik_log_level: INFO
        traefik_metrics_enabled: true
        vaultwarden_image: vaultwarden/server
        vaultwarden_image_tag: "1.35.7"
        vaultwarden_container_name: vaultwarden
        vaultwarden_signups_allowed: false
        timezone: UTC
        traefik_enabled: true
        vaultwarden_enabled: true
        traefik_image_pull_policy: never
        vaultwarden_image_pull_policy: never
        docker_custom_network_name: proxy_net
        docker_custom_network_subnet: "10.203.57.0/24"
        docker_custom_network_gateway: "10.203.57.1"
  playbooks:
    converge: converge.yml
    verify: verify.yml
verifier:
  name: ansible
